config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :vets
  root 'sessions#home'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  resources :users
  get 'auth/facebook/callback' => 'sessions#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :pets

  resources :vets do
    resources :pets, only:[:new, :create, :index]
    resources :reviews, only:[:new, :create, :index]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, :species, presence: true
  validates :name, length: { minimum: 3,
    too_long: "%{count} characters is the minimum allowed" }

  belongs_to :user
  # pet.user - it has a writer and reader of just user
  belongs_to :vet#, optional: true

  #accepts_nested_attributes_for :vet

  # belongs to where you dont want dupplicates - it is best to
  # create a custome one
  def vet_attributes=(attributes)
    vet = Vet.find_or_create_by(attributes)
    self.vet = vet if vet.valid? || !self.vet
  end



  scope :order_by_age, -> {order(:age)}
  scope :order_by_animals, -> {where("age > ?",7)}
  scope :dogs, -> {where(species: "Dog")}
  scope :cats, -> {where(species: "Cat")}
  scope :fish, -> {where(species: "Fish")}
  scope :search_by_age, -> (search_age){where("age = ?", search_age)}

  # def self.order_by_age
  #   order(:age)
  # end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, :content, presence: true
  validates :rating, numericality:{less_than_or_equal_to: 10,
    greater_than:0, only_integer: true}

  belongs_to :vet
  belongs_to :reviewer, class_name: "User"

  def self.average_rating
    average(:rating)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :pets
  has_many :vets, through: :pets
  has_many :reviews, foreign_key: "reviewer_id", class_name: "Review"
  has_many :reviewed_vets, through: :reviews, source: :vet


  validates :username, presence: true
  validates :username, uniqueness: true
  has_secure_password #password validations
end

app/models/vet.rb
class Vet < ApplicationRecord
  has_many :pets
  has_many :users, through: :pets
  has_many :reviews
  has_many :reviewers, through: :reviews, source: :reviewer
  validates :name, :location, :speciality, presence: true
  validates_uniqueness_of :name, scope: :location


  #validates :name, uniqueness: true
  #validates :name, :location, :speciality, presence: true

  def self.most_pets
    joins(:pets).group(:id).order('COUNT(pets.id) DESC').limit(3)
  end



  #validate :duplicate
  # def duplicate
  #   if Vet.find_by(name: name, location: location)
  #     errors.add(:name, "This Vet has already been created")
  #   end
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 include ApplicationHelper
 
  private
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def check_for_logged_in
    redirect_to '/' if !logged_in?
  end


end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def new
    # check if its nested & it's a proper id
    if params[:vet_id] && vet = Vet.find_by_id(params[:vet_id])
      #nested route
      @pet = vet.pets.build #has_many

    else
      #unnested
      @pet = Pet.new
      @pet.build_vet #belongs_to
    end
  end

  def create
    # the following creates a pet and
    # automatically associates it to the current user

    # take my current user and instantiate a new pet that knows about
    # the current user
    @pet = current_user.pets.build(pet_params)
    if @pet.save
      redirect_to pet_path(@pet)
    else
      @pet.build_vet #belongs_to
      render :new
    end
  end

  def index
    if params[:vet_id] && vet = Vet.find_by_id(params[:vet_id])
      #nested route
      @pets = vet.pets
    else
      if params[:age]
        @pets = Pet.search_by_age(params[:age]).order_by_age
        @pets = Pet.order_by_age if @pets == []
      else
        @pets = Pet.order_by_age
      end
    end

  end

  def show
    set_pet
  end

  def edit
    set_pet
  end

  def update
    set_pet
    if @pet.update(pet_params)
      redirect_to pet_path(@pet)
    else
      render :edit
    end
  end

  def destroy
    set_pet
    @pet.destroy
    redirect_to pets_path
  end

  private

  def set_pet
    @pet = Pet.find_by(id: params[:id])
    if !@pet
      redirect_to pets_path
    end
  end

  def pet_params
    params.require(:pet).permit(:name, :species, :age, :vet_id, vet_attributes: [:name, :location, :speciality])
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :check_for_logged_in, only: [:new, :create, :edit, :update]

  def index
    # when ever we have a nested route our parameter
    # will be a vet_id
    @vet = Vet.find_by_id(params[:vet_id])
    if @vet
      @reviews = @vet.reviews
    else
      redirect_to vets_path
    end
  end

  def new
    @vet = Vet.find_by_id(params[:vet_id])
    #@review = Review.new(vet: @vet)
    @review = @vet.reviews.build

  end

  #unnested
  def create
    byebug
    #@vet = Vet.find_by_id(params[:vet_id])
    @review = current_user.reviews.build(review_params)
    if @review.save
      redirect_to vet_path(@review.vet)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating, :vet_id)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
    render :login
  end

  def create
    # find the user that want to log in 56:33
    @user = User.find_by(username: params[:user][:username])
    # if we find the user and authenticate it's password then
    if @user && @user.authenticate(params[:user][:password])
      # sign them in
      session[:user_id] = @user.id
      redirect_to pets_path
    else
      flash[:error] = "Sorry, your username or password was incorrect"
      redirect_to '/login'
    end
  end

  def home
  end

  #logout
  def destroy
    session.clear
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


#loading the signup form
def new
  @user = User.new
end

#signup
def create
  @user = User.new(user_params)
  if @user.save
    #login the user
    session[:user_id] = @user.id
    redirect_to pets_path
  else
    render :new
  end
end

private

def user_params
  params.require(:user).permit(:username, :email, :password)
end

end

app/controllers/vets_controller.rb
class VetsController < ApplicationController

  def index
    @vets = Vet.all
  end

  def show
    @vet = Vet.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vets_helper.rb
module VetsHelper
end

app/views/layouts/_errors.html.erb
<ul>
<% object.errors.full_messages.each do |error_message| %>

  <li><%= error_message %></li>

<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pets</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to 'Log Out', logout_path, method: :delete %>
      <%= link_to 'All Pets', pets_path %>
      <%= link_to 'New Pet', new_pet_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%= form_for(@pet) do |f| %>

<%= render partial: 'layouts/errors', locals: {object: @pet} %>


  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :species %>
  <%= f.select(:species, ["Dog", "Cat", "Fish"]) %>

  <%= f.label :age %>
  <%= f.number_field :age, min:0 %>

  <br><br>

  <%= f.label :vet_id, "Select a Vet" %>
  <%= f.collection_select :vet_id, Vet.all, :id, :name, prompt: true %>

  <br><br>

<% if !params[:vet_id] %>
  <h4>Or add a new vet:</h4>

  <%= f.fields_for :vet do |v| %>
    <%= v.label :name%>
    <%= v.text_field :name %>

    <%= v.label :location%>
    <%= v.text_field :location %>

    <%= v.label :speciality%>
    <%= v.text_field :speciality %>
  <% end %>
<% end %>

  <br><br>
  <%= f.submit %>

  <% end %>

app/views/pets/edit.html.erb
<h1>Edit Pet!</h1>


<%= form_for(@pet) do |f| %>

<%= render partial: 'layouts/errors', locals: {object: @pet} %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :species %>
  <%= f.select(:species, ["Dog", "Cat", "Fish"]) %>

  <%= f.label :age %>
  <%= f.number_field :age, min:0 %>

  <%= f.submit %>

  <% end %>

app/views/pets/index.html.erb
<h1>All the Pets!</h1>

<%= form_tag("/pets", method: "get") do %>
  <%= label_tag(:age, "Enter the age you want to see") %>
  <%= number_field_tag(:age) %>
  <%= submit_tag("Search") %>
<% end %>

<h3>Dogs:</h3>
<%@pets.dogs.each do |pet|%>
<p><%= link_to pet.name, pet_path(pet) %>
   - <%= pet.age %> - owner:<%= pet.user.try(:username) %> - vet: <%= pet.vet.try(:name) %> </p>
<%end%>

<h3>Cats:</h3>
<%@pets.cats.each do |pet|%>
<p><%= link_to pet.name, pet_path(pet) %> - <%= pet.age %> - owner:<%= pet.user.try(:username) %> - vet: <%= pet.vet.try(:name) %> </p>
<%end%>

<h3>Fish:</h3>
<%@pets.fish.each do |pet|%>
<p><%= link_to pet.name, pet_path(pet) %> - <%= pet.age %> - owner:<%= pet.user.try(:username) %> - vet: <%= pet.vet.try(:name) %> </p>
<%end%>

app/views/pets/new.html.erb
<h1>Create a Pet!</h1>

<%= render 'form' %>

app/views/pets/show.html.erb
<h1>One Pet</h1>

<p><%= @pet.name %> is a <%= @pet.species %>
and is <%= @pet.age %> years old. </p>


<%= link_to "Edit Pet", edit_pet_path(@pet) %>
<%= link_to "Delete Pet", pet_path(@pet), method: :delete %>

app/views/reviews/index.html.erb
<h1>Here are the reviews for <%= @vet.name %></h1>

<ul>
  <% @reviews.each do |r| %>
  <li><strong><% r.rating %></strong> <%=r.reviewer.username%>
    says: <%= r.content %> </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>Write your Review for <%= @review.vet.name %></h1>

<%= form_for [@vet, @review] do |f| %>
  <%= f.hidden_field :vet_id %>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div>
    <%= f.label :rating, "from 1-10" %>
    <%= f.number_field :rating, min: 0, max: 10 %>
  </div>
  <br>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>Sign up here!</h1>

<%= form_for(@user) do |f|%>

<%= render partial: 'layouts/errors', locals: {object: @user} %>

<%= f.label :username %>
<%= f.text_field :username %>

<%= f.label :email %>
<%= f.email_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.submit "Sign In" %>


<% end  %>

app/views/vets/new.html.erb
<h1>Edit your Review for <%= @review.vet.name %></h1>

<%= form_for @review do |f| %>
<div>
  <%= f.label :content %>
  <%= f.text_field :content %>
</div>

<div>
  <%= f.label :rating %>
  <%= f.text_field :rating %>
</div>

<%= f.submit %>
<% end %>

app/views/vets/show.html.erb
<h1><%= @vet.name %></h1>

<h2><%= @vet.location %></h2>
<h3>Specialty: <%= @vet.speciality %></h3>
<h4>Average Rating: <%= @vet.reviews.average_rating %></h4>
<p>
  <%= link_to "See all Reviews", vet_reviews_path(@vet.id) %>
  <%= link_to "Write a New Review", new_vet_review_path(@vet.id) %>
</p>

<h4>Clients:</h4>
<ul>
  <% @vet.pets.order_by_age.each do |pet| %>
  <li>
    <%= pet.name %> - <%= pet.age %> - order: <%= pet.user.try(:username) %>
  </li>
  <% end %>
</ul>